# https://docs.travis-ci.com/user/languages/r/

language: r
sudo: false
cache: packages
warnings_are_errors: false

r:
- 3.3
- oldrel
- release
- devel

r_packages:
  - covr

after_success:
- Rscript -e 'covr::codecov()'
